//episode
export const TV_SHOW__EPISODE__FETCH = 'TV_SHOW/EPISODE/FETCH';
export const TV_SHOW__EPISODE__FETCH_COMPLETED = 'TV_SHOW/EPISODE/FETCH_COMPLETED';
export const TV_SHOW__EPISODE__UPDATE = 'TV_SHOW/EPISODE/UPDATE';