//details
export const TV_SHOW__DETAILS__FETCH = 'TV_SHOW/DETAILS/FETCH';
export const TV_SHOW__DETAILS__FETCH_COMPLETED = 'TV_SHOW/DETAILS/FETCH_COMPLETED';
export const TV_SHOW__DETAILS__UPDATE = 'TV_SHOW/DETAILS/UPDATE';

//episodes
export const TV_SHOW__EPISODES__FETCH = 'TV_SHOW/EPISODES/FETCH';
export const TV_SHOW__EPISODES__FETCH_COMPLETED = 'TV_SHOW/EPISODES/FETCH_COMPLETED';
export const TV_SHOW__EPISODES__UPDATE = 'TV_SHOW/EPISODES/UPDATE';